### PR TITLE
Updating to reflect current chisel practices

### PR DESCRIPTION
**Pull request by chick**
- Changed website link
- in general replaced `width =` with just value.W
- removed no-longer-required `dummy` arguments
- a number of other small updates

### CODE REVIEW

**Comment by chick** [comment]
@ccelio Here's my first try, let me know what you think.

**Review by ccelio — APPROVED** [review]

**Comment by ccelio** [comment]
Thanks a bunch!

**Comment by ccelio** [comment]
I’m going to merge as-is, but I’ve been pondering the style of explicitly stating ‘width=‘ despite the added verbosity and redundancy. 

I find U vs W not very distinctive when it comes to visually parsing the two.  I’ve also posted to chisel issues in the past regarding errors like 0.U(16), to which specifying ‘width=‘ is one more level of protection.  :shrug:

**Comment by chick** [comment]
Thanks. 
And yes, I consider the ` 0.U(16)` problem to be particularly ugly, I keep trying to think of some way fix that one.

**Pull request merged**
